services:
  gateway-service:
    image: gateway-service
    container_name: gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - primes-service
    environment:
      - SERVER_PORT=8080

  prime-service-database:
    image: postgres:alpine
    container_name: prime-database
    ports:
      - "5001:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prime

  prime-service:
    image: prime-service
    build:
      context: ../prime-service
      dockerfile: Dockerfile
    container_name: prime-service
    ports:
      - "4001:8080"
    environment:
      - server.port=8080
      - spring.datasource.url=jdbc:postgresql://prime-database:5432/prime
      - spring.datasource.username=postgres
      - spring.datasource.password=password
    restart: "no"
    depends_on:
      - demo-database