name: Test, Create Image, Publish to Azure

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: admin2024
          POSTGRES_PASSWORD: p4662024!
          POSTGRES_DB: primes
        ports:
          - 5001:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      VERSION: ${{ secrets.SERVICE_VERSION }}
      CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      CONTAINER_REGISTRY_UN: ${{ secrets.CONTAINER_REGISTRY_UN }}
      CONTAINER_REGISTRY_PW: ${{ secrets.CONTAINER_REGISTRY_PW }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      DATASOURCE_UN: ${{ secrets.SPRING_DATASOURCE_UN }}
      DATASOURCE_PW: ${{ secrets.SPRING_DATASOURCE_PW }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package
        run: ./mvnw --batch-mode -DskipTests clean package

      - name: Run the unit tests
        run: |
          ./mvnw --batch-mode -Dmaven.test.failure.ignore=true test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5001/primes
          SPRING_DATASOURCE_USERNAME: admin2024
          SPRING_DATASOURCE_PASSWORD: p4662024!

      - name: Report the result of the unit tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      # Build the Docker image
      - name: Build the docker image
        run: ./scripts/build-image.sh

      # Publish the Docker image to GitHub Container Registry
      - name: Publish to Github container registry
        run: ./scripts/push-to-ghcr.sh

      # Publish the Docker image to Azure Container Registry
      - name: Publish to Azure container registry
        run: ./scripts/push-to-acr.sh

      # Install Kubectl and connect it to the cluster
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      # Deploy the service to the Azure cluster
      - name: Deploy
        run: ./scripts/deploy.sh
